export function advanceDue(value,frequency){const d=new Date(value+'T12:00:00Z');if(frequency==='Weekly')d.setUTCDate(d.getUTCDate()+7);else{const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+({Monthly:1,Quarterly:3,Annual:12}[frequency]||1));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));}return d.toISOString().slice(0,10);}
export function createOperations({get,all,run,transaction,id,now,fail,text,note,date,roles,property,entity,work,audit,body,json,communications,template,readBytes,putBytes}){
 async function activeStaff(user,uid,p){const u=await get("SELECT * FROM users WHERE id=? AND organization_id=? AND active=1 AND role IN ('admin','employee')",uid,user.organization_id);if(!u)fail(422,'Choose an active staff member.');await property(u,p,'operate');return u;}
 async function data(user){
  const visible=async(rows)=>{const result=[];for(const r of rows){try{await property(user,r.property_id,user.role==='vendor'?'job':'read');if(user.role==='vendor'&&r.vendor_id!==user.vendor_id)continue;result.push(r);}catch{}}return result;};
  return {backup:user.role==='admin'?(await get('SELECT day,status,completed_at FROM backup_runs ORDER BY day DESC LIMIT 1')||null):null,approvals:await visible(await all('SELECT a.*,w.title,w.property_id,w.vendor_id,u.name decision_by_name FROM spending_approvals a JOIN work_orders w ON w.id=a.work_order_id LEFT JOIN users u ON u.id=a.decided_by WHERE a.organization_id=? ORDER BY a.created_at DESC',user.organization_id)),followups:await visible(await all('SELECT f.*,i.property_id,w.status,w.title FROM inspection_followups f JOIN inspections i ON i.id=f.inspection_id JOIN properties p ON p.id=i.property_id JOIN work_orders w ON w.id=f.work_order_id WHERE p.organization_id=?',user.organization_id)),plans:['admin','employee'].includes(user.role)?await visible(await all('SELECT s.*,u.name assigned_name FROM inspection_plans s JOIN properties p ON p.id=s.property_id JOIN users u ON u.id=s.assigned_to WHERE p.organization_id=?',user.organization_id)):[],automation:user.role==='admin'?(await get('SELECT * FROM automation_settings WHERE organization_id=?',user.organization_id)||{enabled:0}):null,email:user.role==='admin'?await all('SELECT id,email,subject,status,attempts,created_at FROM email_outbox WHERE organization_id=? ORDER BY created_at DESC LIMIT 100',user.organization_id):[]};
 }
 async function blocked(workId){const last=await get('SELECT status FROM spending_approvals WHERE work_order_id=? ORDER BY created_at DESC,id DESC LIMIT 1',workId);return last&&['pending','declined'].includes(last.status);}
 async function handle(req,res,url,user){if(!url.pathname.startsWith('/api/operations'))return false;if(!user)fail(401,'Please sign in.');const p=url.pathname;
  if(req.method==='GET'&&p==='/api/operations'){json(res,200,await data(user));return true;}
  if(req.method!=='POST')fail(404,'Endpoint not found.');const b=await body(req);let result={ok:true};
  if(p==='/api/operations/followup'){
   roles(user,'admin','employee');
   result=await transaction(async()=>{const i=await entity(user,'inspections',b.inspectionId,'operate');if(i.status!=='published')fail(409,'Publish the inspection before creating follow-up work.');const a=JSON.parse(i.answers).find(a=>a.key===b.answerKey&&['attention','monitor'].includes(a.status));if(!a)fail(422,'Choose an Attention or Monitor finding.');const old=await get('SELECT work_order_id FROM inspection_followups WHERE inspection_id=? AND answer_key=?',i.id,a.key);if(old)return {id:old.work_order_id};const key=id();await run('INSERT INTO work_orders(id,property_id,title,description,priority,due_date,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)',key,i.property_id,a.label,`Inspection ${i.inspection_date}: ${a.section}\n${a.note||'No observation recorded.'}`,a.status==='attention'?'High':'Normal',b.dueDate?date(b.dueDate):'',user.id,now());await run('INSERT INTO inspection_followups VALUES(?,?,?,?,?)',i.id,a.key,key,user.id,now());
    // Copy evidence into separate work files. The published report stays immutable.
    for(const f of await all('SELECT * FROM files WHERE inspection_id=?',i.id)){const fid=id(),storageKey=fid;await putBytes(storageKey,await readBytes(f.storage_key),f.mime);await run('INSERT INTO files VALUES(?,?,?,?,?,?,?,?,?,?,?)',fid,i.property_id,null,key,f.name,f.mime,f.bytes,storageKey,'client',user.id,now());await run('INSERT INTO work_evidence_sources VALUES(?,?)',fid,i.id);}
    await audit(user,'inspection.followup_created',key);await communications.work(user,key);return {id:key};});
  }else if(p==='/api/operations/approval'){
   roles(user,'admin');result=await transaction(async()=>{const w=await work(user,b.workId);if(['completed','cancelled'].includes(w.status))fail(409,'Choose an active work order.');if(await get("SELECT id FROM spending_approvals WHERE work_order_id=? AND status='pending'",w.id))fail(409,'An approval is already pending.');const amount=Number(b.amountMinor);if(!Number.isSafeInteger(amount)||amount<1||amount>100000000)fail(422,'Enter an amount between $0.01 and $1,000,000.');const prop=await property(user,w.property_id);const recipients=await all("SELECT id,email FROM users WHERE organization_id=? AND client_id=? AND role='client' AND active=1",user.organization_id,prop.client_id);if(!recipients.length)fail(422,'Invite a client in this family before requesting approval.');const key=id();await run('INSERT INTO spending_approvals(id,organization_id,work_order_id,amount_minor,description,created_by,created_at) VALUES(?,?,?,?,?,?,?)',key,user.organization_id,w.id,amount,text(b.description,'Estimate and scope',4000),user.id,now());await communications.enqueue(user.organization_id,'approval:'+key,recipients,'Approval requested: '+w.title,'A repair estimate needs your decision. Sign in to review the scope and amount before approving or declining.',w.id);await audit(user,'approval.requested',key);return {id:key};});
  }else if(p==='/api/operations/approval-decision'){
   result=await transaction(async()=>{const a=await get('SELECT * FROM spending_approvals WHERE id=? AND organization_id=?',b.id,user.organization_id);if(!a)fail(404,'Approval not found.');const w=await work(user,a.work_order_id);await property(user,w.property_id);if(b.decision==='cancelled')roles(user,'admin');else{roles(user,'client');if(!['approved','declined'].includes(b.decision))fail(422,'Choose approve or decline.');}if(a.status!=='pending'||a.version!==b.version)fail(409,'This estimate was already updated. Refresh before continuing.');await run('UPDATE spending_approvals SET status=?,decided_by=?,decided_at=?,decision_note=?,version=version+1 WHERE id=?',b.decision,user.id,now(),note(b.note),a.id);await communications.enqueue(user.organization_id,'approval-decision:'+a.id,[await communications.primary(user.organization_id)],'Estimate '+b.decision+': '+w.title,'The client approval request has been updated. Sign in to review the decision.',w.id);await audit(user,'approval.'+b.decision,a.id);return {ok:true};});
  }else if(p==='/api/operations/inspection-plan'){
   roles(user,'admin');const prop=await property(user,b.propertyId,'operate');const days=Number(b.intervalDays);if(!Number.isInteger(days)||days<1||days>3650)fail(422,'Enter an interval from 1 to 3650 days.');await activeStaff(user,b.assignedTo,prop.id);const due=date(b.nextDue);await transaction(async()=>{await run('INSERT INTO inspection_plans(id,property_id,assigned_to,interval_days,next_due,active,created_by,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(property_id) DO UPDATE SET assigned_to=excluded.assigned_to,interval_days=excluded.interval_days,next_due=excluded.next_due,active=excluded.active',id(),prop.id,b.assignedTo,days,due,b.active===false?0:1,user.id,now());await audit(user,'inspection.plan_saved',prop.id);});
  }else if(p==='/api/operations/automation'){
   roles(user,'admin');await run('INSERT INTO automation_settings(organization_id,enabled) VALUES(?,?) ON CONFLICT(organization_id) DO UPDATE SET enabled=excluded.enabled',user.organization_id,b.enabled?1:0);await audit(user,'automation.updated',user.organization_id);
  }else if(p==='/api/operations/run'){
   roles(user,'admin');await tick(user.organization_id,true);
  }else fail(404,'Endpoint not found.');json(res,200,result);return true;
 }
 let busy=false;
 async function tick(orgOnly,manual=false){if(busy)return;busy=true;try{
  const orgs=orgOnly?[{organization_id:orgOnly}]:await all('SELECT organization_id FROM automation_settings WHERE enabled=1');
  for(const o of orgs){const org=o.organization_id;try{
   if((await get('SELECT status FROM workspace_settings WHERE organization_id=?',org))?.status==='suspended')continue;const primary=await communications.primary(org);if(!primary)continue;const admin=await get('SELECT * FROM users WHERE id=?',primary.id);const day=now().slice(0,10),soon=new Date(Date.parse(day+'T12:00Z')+3*86400000).toISOString().slice(0,10);
   await transaction(async()=>{
    const plans=await all('SELECT m.* FROM maintenance_plans m JOIN properties p ON p.id=m.property_id WHERE p.organization_id=? AND p.archived_at IS NULL AND m.active=1 AND m.next_due<=?',org,day);
    for(const m of plans){const existing=await get('SELECT work_order_id FROM maintenance_occurrences WHERE plan_id=? AND due_date=?',m.id,m.next_due);if(!existing){const key=id();await run('INSERT INTO work_orders(id,property_id,title,due_date,created_by,created_at) VALUES(?,?,?,?,?,?)',key,m.property_id,m.title,m.next_due,admin.id,now());await run('INSERT INTO maintenance_occurrences VALUES(?,?,?,?)',id(),m.id,m.next_due,key);const prop=await property(admin,m.property_id);if(prop.account_manager_id&&await get('SELECT id FROM users WHERE id=? AND active=1',prop.account_manager_id))await run('INSERT INTO work_staff(work_id,user_id) VALUES(?,?)',key,prop.account_manager_id);await audit(admin,'maintenance.auto_created',key);await communications.work(admin,key);}
     let next=advanceDue(m.next_due,m.frequency);while(next<=day)next=advanceDue(next,m.frequency);await run('UPDATE maintenance_plans SET next_due=? WHERE id=?',next,m.id);
    }
    const inspections=await all('SELECT s.* FROM inspection_plans s JOIN properties p ON p.id=s.property_id WHERE p.organization_id=? AND p.archived_at IS NULL AND s.active=1 AND s.next_due<=?',org,day);
    for(const s of inspections){const assigned=await get('SELECT * FROM users WHERE id=? AND active=1 AND organization_id=?',s.assigned_to,org);try{await property(assigned,s.property_id,'operate');}catch{continue;}const exists=await get('SELECT inspection_id FROM inspection_occurrences WHERE plan_id=? AND due_date=?',s.id,s.next_due);if(!exists){const key=id();await run('INSERT INTO inspections(id,property_id,inspector_id,inspection_date,answers,created_at) VALUES(?,?,?,?,?,?)',key,s.property_id,assigned.id,s.next_due,JSON.stringify(template),now());await run('INSERT INTO inspection_occurrences VALUES(?,?,?)',s.id,s.next_due,key);await communications.enqueue(org,'inspection-created:'+key,[assigned,primary],'Inspection assigned','Your next inspection is ready. Sign in to open the draft.',key);await audit(admin,'inspection.auto_created',key);}let next=s.next_due;do{next=new Date(Date.parse(next+'T12:00Z')+s.interval_days*86400000).toISOString().slice(0,10);}while(next<=day);await run('UPDATE inspection_plans SET next_due=? WHERE id=?',next,s.id);}
    for(const w of await all("SELECT w.* FROM work_orders w JOIN properties p ON p.id=w.property_id WHERE p.organization_id=? AND p.archived_at IS NULL AND w.status NOT IN ('completed','cancelled') AND w.due_date<>'' AND w.due_date<=?",org,soon)){const targets=await all('SELECT u.id,u.email FROM users u JOIN work_staff s ON s.user_id=u.id WHERE s.work_id=? AND u.active=1',w.id);if(w.vendor_id)targets.push(...await all('SELECT id,email FROM users WHERE vendor_id=? AND organization_id=? AND active=1',w.vendor_id,org));const overdue=w.due_date<day;if(overdue)targets.push(primary);await communications.enqueue(org,`work-reminder:${w.id}:${w.due_date}:${overdue?'overdue':'soon'}`,targets,(overdue?'Overdue work: ':'Work due soon: ')+w.title,'Sign in to review the due date and update progress.',w.id);}
    for(const i of await all("SELECT i.* FROM inspections i JOIN properties p ON p.id=i.property_id WHERE p.organization_id=? AND p.archived_at IS NULL AND i.status='draft' AND i.inspection_date<=?",org,soon)){const overdue=i.inspection_date<day;await communications.enqueue(org,`inspection-reminder:${i.id}:${overdue?'overdue':'soon'}`,[await get('SELECT id,email FROM users WHERE id=? AND active=1',i.inspector_id),...(overdue?[primary]:[])],overdue?'Inspection overdue':'Inspection due soon','Sign in to complete the inspection draft.',i.id);}
    await run('INSERT INTO automation_settings(organization_id,last_run,last_error) VALUES(?,?,?) ON CONFLICT(organization_id) DO UPDATE SET last_run=excluded.last_run,last_error=excluded.last_error',org,now(),'');
   });
  }catch(error){await run('UPDATE automation_settings SET last_error=? WHERE organization_id=?','The last run failed. Review the server logs and retry.',org);console.error('Automation run failed:',error.message);if(manual)throw error;}}
 }finally{busy=false;}}
 return {handle,data,blocked,tick};
}
