// Small dependency-free PDF writer for text and JPEG inspection evidence.
// Keeps report generation available without a CDN or a client-side print dialog.
function pdfText(s){return String(s??'').replace(/[–—]/g,'-').replace(/[^\x20-\x7e\n]/g,'?').replace(/([\\()])/g,'\\$1');}
function wrap(text,width=88){return String(text??'').split('\n').flatMap(line=>{const words=line.split(/\s+/),out=[];let current='';for(let word of words){while(word.length>width){if(current){out.push(current);current='';}out.push(word.slice(0,width));word=word.slice(width);}if((current+' '+word).trim().length>width){out.push(current);current=word;}else current=(current+' '+word).trim();}out.push(current);return out;});}
export function jpegSize(bytes){if(bytes[0]!==255||bytes[1]!==216)throw Error('JPEG required');let pos=2;while(pos<bytes.length){if(bytes[pos++]!==255)continue;let marker=bytes[pos++];while(marker===255)marker=bytes[pos++];if(marker===217||marker===218)break;const length=bytes.readUInt16BE(pos);if([192,193,194].includes(marker)){const height=bytes.readUInt16BE(pos+3),width=bytes.readUInt16BE(pos+5),channels=bytes[pos+7];if(!width||!height||width*height>40000000||![1,3].includes(channels))throw Error('Unsupported JPEG');return {height,width,channels};}if(length<2)break;pos+=length;}throw Error('Invalid JPEG');}
export function inspectionPdf(report,photos=[]){
 const objects=[];const add=value=>{objects.push(value);return objects.length;};
 const catalog=add(''),pagesRoot=add(''),font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
 const pages=[];
 const makePage=(stream,resources='')=>{const content=Buffer.from(stream,'latin1');const streamId=add(Buffer.concat([Buffer.from(`<< /Length ${content.length} >>\nstream\n`),content,Buffer.from('\nendstream')]));pages.push(add(`<< /Type /Page /Parent ${pagesRoot} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R >> ${resources} >> /Contents ${streamId} 0 R >>`));};
 const lines=[report.company,'PROPERTY INSPECTION REPORT',report.property,`Client: ${report.client}`,`Inspection: ${report.id}`,`Date: ${report.date} | Inspector: ${report.inspector}`,`Overall condition: ${report.overall}`,'','SUMMARY',...wrap(report.summary),'','CHECKLIST',...report.answers.flatMap(a=>[...wrap(`${a.status.toUpperCase()} - ${a.label}`),...(a.note?wrap('Notes: '+a.note):[]),'']),'CLIENT-VISIBLE NOTES',...wrap(report.notes)];
 for(let pos=0;pos<lines.length;pos+=47){const group=lines.slice(pos,pos+47);let stream='BT /F1 10 Tf 48 748 Td 14 TL\n';group.forEach((line,i)=>{if(i)stream+='T*\n';stream+=`(${pdfText(line)}) Tj\n`;});stream+='ET\n';makePage(stream);}
 photos.forEach((photo,i)=>{const dimensions=jpegSize(photo.bytes);const imageId=add(Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${dimensions.width} /Height ${dimensions.height} /ColorSpace /${dimensions.channels===1?'DeviceGray':'DeviceRGB'} /BitsPerComponent 8 /Filter /DCTDecode /Length ${photo.bytes.length} >>\nstream\n`),photo.bytes,Buffer.from('\nendstream')]));const scale=Math.min(516/dimensions.width,620/dimensions.height);const w=dimensions.width*scale,h=dimensions.height*scale;makePage(`BT /F1 11 Tf 48 748 Td (${pdfText(report.property+' - Inspection photo '+(i+1))}) Tj ET\nq ${w} 0 0 ${h} 48 ${710-h} cm /Image${i} Do Q\nBT /F1 9 Tf 48 52 Td (${pdfText(photo.name)}) Tj ET`, `/XObject << /Image${i} ${imageId} 0 R >>`);});
 objects[catalog-1]=`<< /Type /Catalog /Pages ${pagesRoot} 0 R >>`;objects[pagesRoot-1]=`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map(id=>id+' 0 R').join(' ')}] >>`;
 const parts=[Buffer.from('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n','latin1')],offsets=[0];let size=parts[0].length;
 objects.forEach((obj,i)=>{offsets.push(size);const chunk=Buffer.concat([Buffer.from(`${i+1} 0 obj\n`),Buffer.isBuffer(obj)?obj:Buffer.from(obj),Buffer.from('\nendobj\n')]);parts.push(chunk);size+=chunk.length;});
 parts.push(Buffer.from(`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${size}\n%%EOF`));return Buffer.concat(parts);
}
