// Encrypted full-instance archives. Restore is restricted to a NEW local directory.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,scryptSync,createCipheriv,createDecipheriv,createHash} from 'node:crypto';
import {Readable} from 'node:stream';
import {pipeline} from 'node:stream/promises';
import {createGzip,createGunzip} from 'node:zlib';
import readline from 'node:readline';
import {openDatabase} from './database.mjs';
import {openStorage} from './storage.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
function password(){const p=process.env.ESTATEOS_BACKUP_PASSWORD;if(!p||p.length<16)throw Error('Set ESTATEOS_BACKUP_PASSWORD to at least 16 characters.');return p;}
async function tables(db){return db.kind==='postgres'?(await db.all("SELECT table_name name FROM information_schema.tables WHERE table_schema='estateos' AND table_type='BASE TABLE' ORDER BY table_name")).map(r=>r.name):(await db.all("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")).map(r=>r.name);}
export async function backup(target,env=process.env){const pass=password();const salt=randomBytes(16),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',scryptSync(pass,salt,32),iv),header=Buffer.concat([Buffer.from('EA-BACKUP-1\n'),salt,iv]);let db;const out=fs.createWriteStream(target,{flags:'wx',mode:0o600});out.write(header);try{db=await openDatabase(root,env);const storage=await openStorage(root,env);await db.transaction(async()=>{const names=(await tables(db)).filter(n=>n!=='schema_migrations'&&n!=='sessions');async function* records(){yield JSON.stringify({type:'manifest',version:1,createdAt:new Date().toISOString(),tables:names})+'\n';for(const name of names){if(!/^[a-z_]+$/.test(name))throw Error('Unexpected table name');for(const row of await db.all('SELECT * FROM '+name))yield JSON.stringify({type:'row',table:name,row})+'\n';}for(const f of await db.all('SELECT storage_key FROM files')){const bytes=await storage.read(f.storage_key);yield JSON.stringify({type:'file',key:f.storage_key,sha256:createHash('sha256').update(bytes).digest('hex'),base64:bytes.toString('base64')})+'\n';}}await pipeline(Readable.from(records()),createGzip(),cipher,out,{end:false});});out.end(cipher.getAuthTag());await new Promise((resolve,reject)=>{out.on('finish',resolve);out.on('error',reject);});return {archive:target};}finally{await db?.close();}}
export async function restore(target,destination){const pass=password();if(fs.existsSync(destination))throw Error('Restore requires a new, empty destination path.');const stat=fs.statSync(target),fd=fs.openSync(target,'r'),header=Buffer.alloc(40),tag=Buffer.alloc(16);fs.readSync(fd,header,0,40,0);fs.readSync(fd,tag,0,16,stat.size-16);fs.closeSync(fd);if(header.subarray(0,12).toString()!=='EA-BACKUP-1\n')throw Error('Unknown archive format.');const decipher=createDecipheriv('aes-256-gcm',scryptSync(pass,header.subarray(12,28),32),header.subarray(28,40));decipher.setAuthTag(tag);const localEnv={ESTATEOS_DATA_DIR:destination};let db=await openDatabase(root,localEnv);const allowed=new Set((await tables(db)).filter(n=>!['schema_migrations','sessions'].includes(n)));await db.close();const {DatabaseSync}=await import('node:sqlite');const sqlite=new DatabaseSync(path.join(destination,'estateos.sqlite'));sqlite.exec('PRAGMA foreign_keys=OFF; BEGIN IMMEDIATE');let rows=0,files=0,manifest=false;const decoded=fs.createReadStream(target,{start:40,end:stat.size-17}).pipe(decipher),unzip=createGunzip();const pumping=pipeline(decoded,unzip).catch(error=>{unzip.destroy(error);throw error;});pumping.catch(()=>{});try{const lines=readline.createInterface({input:unzip,crlfDelay:Infinity});for await(const line of lines){const r=JSON.parse(line);if(r.type==='manifest'){if(manifest||r.version!==1||r.tables.some(t=>!allowed.has(t)))throw Error('Archive schema mismatch');manifest=true;}else if(!manifest)throw Error('Missing manifest');else if(r.type==='row'){if(!allowed.has(r.table))throw Error('Unknown table');const columns=Object.keys(r.row);const known=new Set(sqlite.prepare('PRAGMA table_info('+r.table+')').all().map(c=>c.name));if(columns.some(c=>!known.has(c)))throw Error('Unknown column');sqlite.prepare('INSERT INTO '+r.table+'('+columns.join(',')+') VALUES('+columns.map(()=>'?').join(',')+')').run(...columns.map(c=>r.row[c]));rows++;}else if(r.type==='file'){if(!/^[a-zA-Z0-9-]+$/.test(r.key))throw Error('Invalid file key');const bytes=Buffer.from(r.base64,'base64');if(createHash('sha256').update(bytes).digest('hex')!==r.sha256)throw Error('File checksum mismatch');fs.mkdirSync(path.join(destination,'files'),{recursive:true});fs.writeFileSync(path.join(destination,'files',r.key),bytes,{flag:'wx',mode:0o600});files++;}else throw Error('Unknown archive record');}await pumping;if(!manifest||sqlite.prepare('PRAGMA foreign_key_check').all().length)throw Error('Restore integrity check failed');for(const f of sqlite.prepare('SELECT storage_key FROM files').all())if(!fs.existsSync(path.join(destination,'files',f.storage_key)))throw Error('Archive is missing a referenced file');sqlite.exec('COMMIT');return {rows,files,destination};}catch(error){sqlite.exec('ROLLBACK');throw error;}finally{sqlite.close();}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const [command,target,destination]=process.argv.slice(2);try{if(!target||!['backup','restore'].includes(command)||command==='restore'&&!destination)throw Error('Usage: node recovery.mjs backup <archive> OR restore <archive> <new-local-directory>');console.log(JSON.stringify(command==='backup'?await backup(target):await restore(target,destination)));}catch(error){console.error(error.message);process.exitCode=1;}}
