import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {inspectionPdf,jpegSize} from './pdf.mjs';

const root=path.dirname(fileURLToPath(import.meta.url));
const dir=path.resolve(process.env.ESTATEOS_DATA_DIR||path.join(root,'data'));
fs.mkdirSync(path.join(dir,'files'),{recursive:true});
const db=new DatabaseSync(path.join(dir,'estateos.sqlite'));
db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
db.exec(fs.readFileSync(path.join(root,'schema.sql'),'utf8'));
db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)');
for(const migration of fs.readdirSync(path.join(root,'migrations')).filter(name=>name.endsWith('.sql')).sort()){
 if(!db.prepare('SELECT 1 FROM schema_migrations WHERE name=?').get(migration)){
  db.exec('BEGIN IMMEDIATE');
  try{db.exec(fs.readFileSync(path.join(root,'migrations',migration),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(migration,new Date().toISOString());db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}
 }
}
const now=()=>new Date().toISOString(),id=()=>randomUUID(),hash=s=>createHash('sha256').update(s).digest('hex');
const get=(sql,...args)=>db.prepare(sql).get(...args),all=(sql,...args)=>db.prepare(sql).all(...args),run=(sql,...args)=>db.prepare(sql).run(...args);
function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
function fail(status,message){throw Object.assign(new Error(message),{status});}
function text(value,label='Value',max=4000){if(typeof value!=='string'||!value.trim()||value.length>max)fail(422,`${label} is required (maximum ${max} characters).`);return value.trim();}
function note(s,max=4000){if(s==null||s==='')return '';return text(s,'Text',max);}
function addressFields(b){
 const street=text(b.streetAddress,'Street address',200),line2=note(b.addressLine2,120),city=text(b.city,'City',120),state=text(b.state,'State / province',100),postal=text(b.postalCode,'ZIP / postal code',24),country=text(b.country||'United States','Country',100);
 if(['united states','us','usa'].includes(country.toLowerCase())&&!/^\d{5}(-\d{4})?$/.test(postal))fail(422,'Enter a 5-digit ZIP code or ZIP+4.');
 const full=[street,line2,`${city}, ${state} ${postal}`,country].filter(Boolean).join(', ');
 return {street,line2,city,state,postal,country,full};
}
function roomProfile(value){try{const p=typeof value==='string'?JSON.parse(value||'{}'):value||{};const rooms=Array.isArray(p.rooms)?p.rooms.filter(r=>r&&typeof r.key==='string'&&typeof r.name==='string').map(r=>({key:r.key,name:r.name})):[];return {bedrooms:Math.max(0,Number(p.bedrooms)||0),fullBathrooms:Math.max(0,Number(p.fullBathrooms)||0),halfBathrooms:Math.max(0,Number(p.halfBathrooms)||0),rooms};}catch{return {bedrooms:0,fullBathrooms:0,halfBathrooms:0,rooms:[]};}}
function roomStatusFor(p){return roomProfile(p.room_profile).rooms.map(r=>({key:r.key,name:r.name,ready:false,notes:''}));}
function date(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||'')||Number.isNaN(Date.parse(s+'T12:00:00Z'))||new Date(s+'T12:00:00Z').toISOString().slice(0,10)!==s)fail(422,'Choose a valid date.');return s;}
function nextDue(value,frequency){const d=new Date(value+'T12:00:00Z');if(frequency==='Weekly')d.setUTCDate(d.getUTCDate()+7);else if(frequency==='Monthly')d.setUTCMonth(d.getUTCMonth()+1);else if(frequency==='Quarterly')d.setUTCMonth(d.getUTCMonth()+3);else d.setUTCFullYear(d.getUTCFullYear()+1);return d.toISOString().slice(0,10);}
function passwordHash(password){text(password,'Password',200);if(password.length<12)fail(422,'Use a password with at least 12 characters.');const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');}
function passwordMatches(password,saved){try{const [salt,key]=saved.split(':');return timingSafeEqual(Buffer.from(key,'hex'),scryptSync(String(password),salt,64));}catch{return false;}}
function actor(req){const token=(req.headers.cookie||'').match(/(?:^|; )estateos_session=([^;]+)/)?.[1];if(!token)return null;return get('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE token_hash=? AND expires_at>? AND users.active=1',hash(token),Date.now())||null;}
function safeUser(user){return user?{id:user.id,name:user.name,email:user.email,role:user.role}:null;}
function roles(user,...allowed){if(!user)fail(401,'Please sign in.');if(!allowed.includes(user.role))fail(403,'You do not have permission for this action.');}
function property(user,propertyId,operation='read'){
 if(!user)fail(401,'Please sign in.');const p=get('SELECT * FROM properties WHERE id=? AND organization_id=?',propertyId,user.organization_id);if(!p)fail(404,'Residence not found.');
 if(user.role==='admin')return p;
 if(user.role==='client'&&p.client_id===user.client_id&&operation!=='operate')return p;
 if(user.role==='employee'&&get('SELECT 1 FROM property_access WHERE user_id=? AND property_id=?',user.id,p.id))return p;
 if(user.role==='vendor'&&operation==='job'&&get("SELECT 1 FROM work_orders WHERE property_id=? AND vendor_id=? AND status NOT IN ('cancelled')",p.id,user.vendor_id))return p;
 fail(404,'Residence not found.');
}
function entity(user,table,entityId,operation='read'){const row=get(`SELECT * FROM ${table} WHERE id=?`,entityId);if(!row)fail(404,'Record not found.');property(user,row.property_id,operation);return row;}
function work(user,workId){const row=entity(user,'work_orders',workId,user.role==='vendor'?'job':'read');if(user.role==='vendor'&&row.vendor_id!==user.vendor_id)fail(404,'Job not found.');return row;}
function audit(user,action,entityId){run('INSERT INTO audit VALUES(?,?,?,?,?,?)',id(),user.organization_id,user.id,action,entityId,now());}
function notifyProperty(p,title,entityId,audience='staff'){const recipients=all('SELECT * FROM users WHERE organization_id=? AND active=1',p.organization_id).filter(u=>audience==='client'?u.role==='client'&&u.client_id===p.client_id:u.role==='admin'||u.role==='employee'&&get('SELECT 1 FROM property_access WHERE user_id=? AND property_id=?',u.id,p.id));for(const u of recipients)run('INSERT INTO notifications VALUES(?,?,?,?,?,?)',id(),u.id,title,entityId,null,now());}
function json(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data));}
async function body(req){let length=0;const chunks=[];for await(const chunk of req){length+=chunk.length;if(length>15*1024*1024)fail(413,'Upload exceeds 10 MB.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{fail(400,'Invalid request.');}}
const attempts=new Map();function rate(req,kind,max=20){const key=kind+req.socket.remoteAddress;const record=attempts.get(key)||{count:0,end:Date.now()+600000};if(record.end<Date.now()){record.count=0;record.end=Date.now()+600000;}if(++record.count>max)fail(429,'Too many attempts. Please try again later.');attempts.set(key,record);}
function session(res,req,user){const token=randomBytes(32).toString('hex');run('DELETE FROM sessions WHERE expires_at<?',Date.now());run('INSERT INTO sessions VALUES(?,?,?)',hash(token),user.id,Date.now()+8*3600000);const secure=process.env.ESTATEOS_SECURE_COOKIES==='1';res.setHeader('Set-Cookie',`estateos_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${secure?'; Secure':''}`);}
function assertVersion(row,b){if(!Number.isInteger(b.version)||b.version!==row.version)fail(409,'This record changed. Reload it before saving.');}
const template=JSON.parse(fs.readFileSync(path.join(root,'inspection-template.json'),'utf8'));

function snapshot(user){
 const allProperties=all('SELECT properties.*, clients.name client_name FROM properties JOIN clients ON clients.id=properties.client_id WHERE properties.organization_id=? AND properties.archived_at IS NULL',user.organization_id);
 const archivedProperties=user.role==='admin'?all('SELECT properties.*, clients.name client_name FROM properties JOIN clients ON clients.id=properties.client_id WHERE properties.organization_id=? AND properties.archived_at IS NOT NULL ORDER BY properties.archived_at DESC',user.organization_id):[];
 const props=allProperties.filter(p=>{try{property(user,p.id,user.role==='vendor'?'job':'read');return true;}catch{return false;}});
 const allowed=new Set(props.map(p=>p.id));
 const scoped=table=>all(`SELECT * FROM ${table}`).filter(row=>allowed.has(row.property_id));
 let jobs=scoped('work_orders');if(user.role==='vendor')jobs=jobs.filter(j=>j.vendor_id===user.vendor_id);if(user.role==='client')jobs=jobs.map(({description,...j})=>({...j,description:'',service_notes:j.status==='completed'?j.service_notes:''}));
 const inspections=user.role==='vendor'?[]:scoped('inspections').filter(i=>user.role!=='client'||i.status==='published').map(i=>{const {internal_notes,report_snapshot,...visible}=i;return {...visible,answers:JSON.parse(i.answers),...(user.role==='admin'||user.role==='employee'?{internal_notes}: {})};});
 const jobIds=new Set(jobs.map(j=>j.id));const inspectionIds=new Set(inspections.map(i=>i.id));
 const files=scoped('files').filter(f=>fileAllowed(user,f,inspectionIds,jobIds)).map(({storage_key,...f})=>f);
 return {user:safeUser(user),company:get('SELECT name FROM organizations WHERE id=?',user.organization_id).name,properties:props.map(p=>{if(user.role==='vendor')return {id:p.id,name:p.name,address:p.address};if(user.role==='client'){const {manual,...safe}=p;return safe;}return p;}),archivedProperties,clients:user.role==='admin'?all('SELECT * FROM clients WHERE organization_id=?',user.organization_id):[],vendors:['admin','employee'].includes(user.role)?all('SELECT * FROM vendors WHERE organization_id=?',user.organization_id):[],users:user.role==='admin'?all('SELECT id,name,email,role,client_id,vendor_id,active FROM users WHERE organization_id=?',user.organization_id):[],assets:user.role==='vendor'?[]:scoped('assets'),work:jobs,requests:user.role==='vendor'?[]:scoped('requests'),inspections,files,shopping:user.role==='vendor'?[]:scoped('shopping_items'),arrivals:user.role==='vendor'?[]:scoped('arrivals').map(a=>({...a,items:JSON.parse(a.items),room_status:JSON.parse(a.room_status||'[]')})),maintenance:['admin','employee'].includes(user.role)?scoped('maintenance_plans'):[],notes:['admin','employee'].includes(user.role)?scoped('notes'):[],invoices:user.role==='admin'?all('SELECT invoices.*,clients.name client_name,COALESCE((SELECT SUM(amount_minor) FROM payments WHERE invoice_id=invoices.id),0) paid_minor FROM invoices JOIN clients ON clients.id=invoices.client_id WHERE invoices.organization_id=?',user.organization_id):[],audit:user.role==='admin'?all('SELECT audit.*,users.name actor_name FROM audit JOIN users ON users.id=audit.actor_id WHERE audit.organization_id=? ORDER BY audit.created_at DESC LIMIT 100',user.organization_id):[],notifications:all('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100',user.id),template};
}
function fileAllowed(user,f,inspectionIds,jobIds){
 if(['admin','employee'].includes(user.role))return true;
 if(user.role==='vendor')return !!f.work_order_id&&jobIds.has(f.work_order_id);
 if(f.inspection_id)return inspectionIds.has(f.inspection_id)&&get('SELECT status FROM inspections WHERE id=?',f.inspection_id)?.status==='published';
 if(f.work_order_id)return jobIds.has(f.work_order_id)&&get('SELECT status FROM work_orders WHERE id=?',f.work_order_id)?.status==='completed';
 return f.visibility==='client';
}
function readFile(user,fileId){const f=get('SELECT * FROM files WHERE id=?',fileId);if(!f)fail(404,'File not found.');property(user,f.property_id,user.role==='vendor'?'job':'read');const ins=new Set(all("SELECT id FROM inspections WHERE property_id=? AND status='published'",f.property_id).map(x=>x.id));const jobs=new Set(all('SELECT * FROM work_orders WHERE property_id=?',f.property_id).filter(x=>user.role!=='vendor'||x.vendor_id===user.vendor_id).map(x=>x.id));if(!fileAllowed(user,f,ins,jobs))fail(404,'File not found.');return f;}

async function api(req,res,url,user){
 const method=req.method,p=url.pathname;
 if(p==='/api/status'&&method==='GET')return json(res,200,{configured:!!get('SELECT id FROM users LIMIT 1'),user:safeUser(user)});
 if(p==='/api/setup'&&method==='POST'){
  rate(req,'setup');const b=await body(req);if(get('SELECT id FROM users LIMIT 1'))fail(409,'Setup is already complete.');if(process.env.ESTATEOS_HOST&&process.env.ESTATEOS_HOST!=='127.0.0.1'&&b.setupKey!==process.env.ESTATEOS_SETUP_KEY)fail(403,'Setup key required.');const pw=passwordHash(b.password);const email=text(b.email,'Email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(422,'Enter a valid email.');const org=id(),uid=id();transaction(()=>{if(get('SELECT id FROM users LIMIT 1'))fail(409,'Setup complete.');run('INSERT INTO organizations VALUES(?,?,?)',org,text(b.company,'Company',160),now());run('INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?,?)',uid,org,text(b.name,'Name',160),email,pw,'admin',null,null,1,now());});const u=get('SELECT * FROM users WHERE id=?',uid);session(res,req,u);return json(res,201,{user:safeUser(u)});
 }
 if(p==='/api/login'&&method==='POST'){rate(req,'login');const b=await body(req);const u=get('SELECT * FROM users WHERE email=? AND active=1',String(b.email).toLowerCase());if(!u||!passwordMatches(b.password,u.password_hash))fail(401,'Email or password is incorrect.');session(res,req,u);return json(res,200,{user:safeUser(u)});}
 if(p==='/api/accept-invite'&&method==='POST'){rate(req,'invite');const b=await body(req);const invitation=get('SELECT * FROM invitations WHERE token_hash=? AND used_at IS NULL AND expires_at>?',hash(String(b.token)),Date.now());if(!invitation)fail(422,'Invitation expired or already used.');const pw=passwordHash(b.password),uid=id();transaction(()=>{const fresh=get('SELECT * FROM invitations WHERE token_hash=? AND used_at IS NULL',hash(String(b.token)));if(!fresh)fail(409,'Invitation already used.');run('INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?,?)',uid,invitation.organization_id,text(b.name,'Name',160),invitation.email,pw,invitation.role,invitation.client_id,invitation.vendor_id,1,now());run('UPDATE invitations SET used_at=? WHERE token_hash=?',now(),invitation.token_hash);});const u=get('SELECT * FROM users WHERE id=?',uid);session(res,req,u);return json(res,201,{user:safeUser(u)});}
 if(!user)fail(401,'Please sign in.');
 if(p==='/api/logout'&&method==='POST'){const token=(req.headers.cookie||'').match(/estateos_session=([^;]+)/)?.[1];if(token)run('DELETE FROM sessions WHERE token_hash=?',hash(token));res.setHeader('Set-Cookie','estateos_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0');return json(res,200,{ok:true});}
 if(p==='/api/data'&&method==='GET')return json(res,200,snapshot(user));
 if(p.startsWith('/api/files/')&&method==='GET'){const f=readFile(user,p.split('/')[3]);res.writeHead(200,{'Content-Type':f.mime,'Cache-Control':'no-store','Content-Disposition':`inline; filename="${f.name.replace(/[^a-zA-Z0-9._ -]/g,'_')}"`,'Content-Security-Policy':"default-src 'none'; sandbox"});return fs.createReadStream(path.join(dir,'files',f.storage_key)).pipe(res);}
 if(/^\/api\/inspections\/[^/]+\/pdf$/.test(p)&&method==='GET'){const row=entity(user,'inspections',p.split('/')[3]);if(row.status!=='published')fail(409,'Publish the inspection first.');const report=JSON.parse(row.report_snapshot);const photos=report.fileIds.map(fileId=>{const f=readFile(user,fileId);return {name:f.name,bytes:fs.readFileSync(path.join(dir,'files',f.storage_key))};});const pdf=inspectionPdf(report,photos);res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="EstateOS-Inspection-${row.id}.pdf"`,'Cache-Control':'no-store'});return res.end(pdf);}
 if(p==='/api/backup'&&method==='GET'){roles(user,'admin');const tables=['organizations','clients','properties','vendors','assets','work_orders','requests','inspections','files','shopping_items','arrivals','maintenance_plans','invoices','payments','notes','audit'];const backup={version:1,createdAt:now(),tables:{}};for(const table of tables)backup.tables[table]=all(`SELECT * FROM ${table}`);return json(res,200,backup,{'Content-Disposition':'attachment; filename="EstateOS-records.json"'});}
 if(method!=='POST')fail(404,'Endpoint not found.');
 const b=await body(req);let result;
 if(p==='/api/clients'){roles(user,'admin');const key=id();run('INSERT INTO clients VALUES(?,?,?,?,?,?)',key,user.organization_id,text(b.name,'Family name',160),note(b.email,254),note(b.phone,80),now());audit(user,'client.created',key);result={id:key};}
 else if(p==='/api/properties'){roles(user,'admin');if(!get('SELECT id FROM clients WHERE id=? AND organization_id=?',b.clientId,user.organization_id))fail(422,'Select a client family.');const a=addressFields(b),key=id();run('INSERT INTO properties(id,organization_id,client_id,name,address,timezone,manual,created_at,street_address,address_line2,city,state,postal_code,country,room_profile) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',key,user.organization_id,b.clientId,text(b.name,'Residence',160),a.full,note(b.timezone,80)||'America/New_York','',now(),a.street,a.line2,a.city,a.state,a.postal,a.country,JSON.stringify(roomProfile(b.roomProfile)));audit(user,'property.created',key);result={id:key};}
 else if(p==='/api/properties/update'){roles(user,'admin');const row=property(user,b.id,'operate'),a=addressFields(b);run('UPDATE properties SET name=?,address=?,street_address=?,address_line2=?,city=?,state=?,postal_code=?,country=?,room_profile=? WHERE id=?',text(b.name,'Residence',160),a.full,a.street,a.line2,a.city,a.state,a.postal,a.country,JSON.stringify(roomProfile(b.roomProfile)),row.id);audit(user,'property.updated',row.id);result={id:row.id};}
 else if(p==='/api/properties/archive'){roles(user,'admin');const row=property(user,b.id,'operate');if(!b.confirm)fail(422,'Confirm archiving this residence.');run('UPDATE properties SET archived_at=? WHERE id=? AND archived_at IS NULL',now(),row.id);audit(user,'property.archived',row.id);result={id:row.id,archived:true};}
 else if(p==='/api/properties/restore'){roles(user,'admin');const row=get('SELECT * FROM properties WHERE id=? AND organization_id=?',b.id,user.organization_id);if(!row)fail(404,'Residence not found.');run('UPDATE properties SET archived_at=NULL WHERE id=?',row.id);audit(user,'property.restored',row.id);result={id:row.id,archived:false};}
 else if(p==='/api/manual'){roles(user,'admin','employee');property(user,b.propertyId,'operate');run('UPDATE properties SET manual=? WHERE id=?',note(b.manual,16000),b.propertyId);audit(user,'manual.updated',b.propertyId);result={ok:true};}
 else if(p==='/api/vendors'){roles(user,'admin');const key=id();run('INSERT INTO vendors VALUES(?,?,?,?,?,?,?)',key,user.organization_id,text(b.name,'Vendor',160),note(b.trade,100),note(b.email,254),note(b.phone,80),now());audit(user,'vendor.created',key);result={id:key};}
 else if(p==='/api/invitations'){roles(user,'admin');const role=b.role;if(!['admin','employee','client','vendor'].includes(role))fail(422,'Invalid role.');if(role==='client'&&!get('SELECT 1 FROM clients WHERE id=? AND organization_id=?',b.clientId,user.organization_id))fail(422,'Select the client family.');if(role==='vendor'&&!get('SELECT 1 FROM vendors WHERE id=? AND organization_id=?',b.vendorId,user.organization_id))fail(422,'Select the vendor company.');const token=randomBytes(32).toString('hex');const email=text(b.email,'Email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(422,'Enter a valid email.');if(get('SELECT 1 FROM users WHERE email=?',email))fail(409,'That account already exists.');run('INSERT INTO invitations VALUES(?,?,?,?,?,?,?,?)',hash(token),user.organization_id,email,role,role==='client'?b.clientId:null,role==='vendor'?b.vendorId:null,Date.now()+48*3600000,null);audit(user,'invitation.created',email);result={invitePath:'/?invite='+token,expiresInHours:48};}
 else if(p==='/api/access'){roles(user,'admin');const member=get('SELECT * FROM users WHERE id=? AND organization_id=?',b.userId,user.organization_id);if(!member||member.role!=='employee')fail(422,'Select an employee.');property(user,b.propertyId);run('INSERT OR IGNORE INTO property_access VALUES(?,?)',member.id,b.propertyId);audit(user,'access.granted',member.id);result={ok:true};}
 else if(p==='/api/users/suspend'){roles(user,'admin');const member=get('SELECT * FROM users WHERE id=? AND organization_id=?',b.userId,user.organization_id);if(!member||member.id===user.id)fail(422,'Cannot suspend your own account.');run('UPDATE users SET active=0 WHERE id=?',member.id);run('DELETE FROM sessions WHERE user_id=?',member.id);audit(user,'user.suspended',member.id);result={ok:true};}
 else if(p==='/api/assets'){roles(user,'admin','employee');property(user,b.propertyId,'operate');const key=id();run('INSERT INTO assets VALUES(?,?,?,?,?,?,?,?,?)',key,b.propertyId,text(b.name,'Asset',160),note(b.category,100),note(b.model,160),note(b.serial,160),note(b.location,200),note(b.warranty,100),now());audit(user,'asset.created',key);result={id:key};}
 else if(p==='/api/work'){roles(user,'admin','employee');property(user,b.propertyId,'operate');if(b.assetId&&!get('SELECT id FROM assets WHERE id=? AND property_id=?',b.assetId,b.propertyId))fail(422,'Asset belongs to another residence.');if(b.vendorId&&!get('SELECT 1 FROM vendors WHERE id=? AND organization_id=?',b.vendorId,user.organization_id))fail(422,'Unknown vendor.');const key=id();run('INSERT INTO work_orders(id,property_id,asset_id,title,description,priority,due_date,vendor_id,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',key,b.propertyId,b.assetId||null,text(b.title,'Work title',200),note(b.description),['Normal','High','Urgent'].includes(b.priority)?b.priority:'Normal',b.dueDate?date(b.dueDate):'',b.vendorId||null,user.id,now());audit(user,'work.created',key);result={id:key};}
 else if(p==='/api/work/action'){roles(user,'admin','employee','vendor');const row=work(user,b.id);assertVersion(row,b);const transitions={start:['open','scheduled'],submit:['in_progress','open','scheduled'],accept:['submitted'],return:['submitted']};if(!transitions[b.action]?.includes(row.status))fail(409,'That job is not in the right state.');if(['accept','return'].includes(b.action)&&!['admin','employee'].includes(user.role))fail(403,'A staff reviewer must verify completion.');if(b.action==='submit'&&!get('SELECT 1 FROM files WHERE work_order_id=?',row.id))fail(422,'Add at least one completion photo.');const status={start:'in_progress',submit:'submitted',accept:'completed',return:'in_progress'}[b.action];const pRow=property(user,row.property_id,user.role==='vendor'?'job':'operate');transaction(()=>{run('UPDATE work_orders SET status=?,service_notes=?,completed_at=?,version=version+1 WHERE id=?',status,b.action==='submit'?text(b.notes,'Completion notes'):row.service_notes,status==='completed'?now():null,row.id);if(status==='completed'){run("UPDATE requests SET status='completed' WHERE work_order_id=?",row.id);notifyProperty(pRow,'Service completed: '+row.title,row.id,'client');}else if(status==='submitted')notifyProperty(pRow,'Review completion: '+row.title,row.id);audit(user,'work.'+b.action,row.id);});result={ok:true};}
 else if(p==='/api/requests'){roles(user,'admin','employee','client');const pRow=property(user,b.propertyId);const key=id();transaction(()=>{run('INSERT INTO requests VALUES(?,?,?,?,?,?,?,?)',key,pRow.id,user.id,text(b.title,'Request',200),note(b.description),'new',null,now());notifyProperty(pRow,'New request: '+b.title,key);audit(user,'request.created',key);});result={id:key};}
 else if(p==='/api/requests/assign'){roles(user,'admin','employee');const row=entity(user,'requests',b.id,'operate');const job=work(user,b.workId);if(row.property_id!==job.property_id)fail(422,'Choose work at the same residence.');run("UPDATE requests SET work_order_id=?,status='in_progress' WHERE id=?",job.id,row.id);audit(user,'request.assigned',row.id);result={ok:true};}
 else if(p==='/api/inspections'){roles(user,'admin','employee');property(user,b.propertyId,'operate');const key=id();run('INSERT INTO inspections(id,property_id,inspector_id,inspection_date,answers,created_at) VALUES(?,?,?,?,?,?)',key,b.propertyId,user.id,date(b.date),JSON.stringify(template),now());audit(user,'inspection.started',key);result={id:key};}
 else if(p==='/api/inspections/save'){roles(user,'admin','employee');const row=entity(user,'inspections',b.id,'operate');assertVersion(row,b);if(row.status!=='draft')fail(409,'Published reports cannot be edited.');const answers=validateAnswers(b.answers);run('UPDATE inspections SET answers=?,summary=?,notes=?,internal_notes=?,version=version+1 WHERE id=?',JSON.stringify(answers),note(b.summary),note(b.notes),note(b.internalNotes),row.id);audit(user,'inspection.saved',row.id);result={id:row.id,version:row.version+1};}
 else if(p==='/api/inspections/publish'){roles(user,'admin');const row=entity(user,'inspections',b.id,'operate');const key=text(b.idempotencyKey,'Publication key',100),requestHash=hash(JSON.stringify(b));const saved=get('SELECT * FROM idempotency WHERE user_id=? AND key=? AND route=?',user.id,key,p);if(saved){if(saved.request_hash!==requestHash)fail(409,'Publication key reused for a different request.');return json(res,200,JSON.parse(saved.response));}assertVersion(row,b);if(row.status!=='draft')fail(409,'Already published.');const answers=JSON.parse(row.answers);if(!row.summary.trim())fail(422,'Add an inspection summary.');const pRow=property(user,row.property_id);const fileIds=all('SELECT id FROM files WHERE inspection_id=? ORDER BY created_at',row.id).map(f=>f.id);const report={id:row.id,company:get('SELECT name FROM organizations WHERE id=?',user.organization_id).name,property:pRow.name,client:get('SELECT name FROM clients WHERE id=?',pRow.client_id).name,date:row.inspection_date,inspector:get('SELECT name FROM users WHERE id=?',row.inspector_id).name,overall:answers.some(a=>a.status==='attention')?'Action needed':answers.some(a=>a.status==='monitor')?'Monitor':answers.every(a=>a.status==='na')?'Not assessed':'Passed',answers,summary:row.summary,notes:row.notes,fileIds};result={id:row.id,published:true};transaction(()=>{run("UPDATE inspections SET status='published',published_at=?,report_snapshot=?,version=version+1 WHERE id=?",now(),JSON.stringify(report),row.id);notifyProperty(pRow,'Inspection report available: '+pRow.name,row.id,'client');audit(user,'inspection.published',row.id);run('INSERT INTO idempotency VALUES(?,?,?,?,?)',user.id,key,p,requestHash,JSON.stringify(result));});}
 else if(p==='/api/files'){roles(user,'admin','employee','vendor');const pRow=property(user,b.propertyId,user.role==='vendor'?'job':'operate');if(b.inspectionId){roles(user,'admin','employee');const inspection=entity(user,'inspections',b.inspectionId,'operate');if(inspection.property_id!==pRow.id||inspection.status!=='draft')fail(422,'Photos require a draft at this residence.');}if(b.workId){const job=work(user,b.workId);if(job.property_id!==pRow.id||['completed','cancelled','submitted'].includes(job.status))fail(422,'Evidence is locked after submission.');}if(user.role==='vendor'&&!b.workId)fail(403,'Upload evidence to an assigned job.');if(b.inspectionId&&b.workId)fail(422,'Choose one evidence target.');const bytes=Buffer.from(text(b.base64,'File',14*1024*1024),'base64');if(bytes.length>10*1024*1024)fail(413,'Maximum file size is 10 MB.');const isJpeg=bytes[0]===255&&bytes[1]===216;if(isJpeg)jpegSize(bytes);else if(bytes.subarray(0,5).toString()!=='%PDF-'||b.inspectionId||b.workId)fail(422,'Use JPEG photos or PDF documents.');const key=id(),storageKey=id();fs.writeFileSync(path.join(dir,'files',storageKey),bytes,{flag:'wx'});try{run('INSERT INTO files VALUES(?,?,?,?,?,?,?,?,?,?,?)',key,pRow.id,b.inspectionId||null,b.workId||null,text(b.name,'Filename',200),isJpeg?'image/jpeg':'application/pdf',bytes.length,storageKey,b.visibility==='client'?'client':'internal',user.id,now());audit(user,'file.uploaded',key);}catch(e){fs.unlinkSync(path.join(dir,'files',storageKey));throw e;}result={id:key};}
 else if(p==='/api/shopping'){roles(user,'admin','employee','client');property(user,b.propertyId);const key=id();run('INSERT INTO shopping_items VALUES(?,?,?,?,?,?,?)',key,b.propertyId,text(b.name,'Item',200),text(b.quantity||'1','Quantity',80),note(b.category,100),note(b.notes),now());audit(user,'shopping.added',key);result={id:key};}
 else if(p==='/api/arrivals'){roles(user,'admin','employee','client');const pRow=property(user,b.propertyId);if(!b.arrivalAt||Number.isNaN(Date.parse(b.arrivalAt)))fail(422,'Choose arrival date and time.');const ids=Array.isArray(b.itemIds)?b.itemIds:[];const items=ids.map(itemId=>{const item=get('SELECT * FROM shopping_items WHERE id=? AND property_id=?',itemId,pRow.id);if(!item)fail(422,'Shopping item belongs to another residence.');return {id:item.id,name:item.name,quantity:item.quantity,notes:item.notes,status:'requested',substitutionNeeded:false,substitution:''};});const key=id(),roomStatus=roomStatusFor(pRow);transaction(()=>{run('INSERT INTO arrivals(id,property_id,created_by,arrival_at,needs,status,items,created_at,version,room_status) VALUES(?,?,?,?,?,?,?,?,?,?)',key,pRow.id,user.id,b.arrivalAt,note(b.needs),'submitted',JSON.stringify(items),now(),1,JSON.stringify(roomStatus));notifyProperty(pRow,'Arrival preparation requested',key);audit(user,'arrival.created',key);});result={id:key};}
 else if(p==='/api/arrivals/update'){roles(user,'admin','employee');const row=entity(user,'arrivals',b.id,'operate');assertVersion(row,b);const items=JSON.parse(row.items),roomStatus=JSON.parse(row.room_status||'[]');if(b.itemId&&b.itemStatus!==undefined){const item=items.find(i=>i.id===b.itemId);if(!item||!['requested','purchased','stocked'].includes(b.itemStatus))fail(422,'Invalid shopping status.');item.status=b.itemStatus;} if(b.itemId&&b.substitutionNeeded!==undefined){const item=items.find(i=>i.id===b.itemId);if(item){item.substitutionNeeded=!!b.substitutionNeeded;item.substitution=note(b.substitution,500);}}if(b.roomKey){const room=roomStatus.find(r=>r.key===b.roomKey);if(!room)fail(422,'Unknown room.');if(b.roomReady!==undefined)room.ready=!!b.roomReady;if(b.roomNotes!==undefined)room.notes=note(b.roomNotes,500);}let status=b.status||row.status;if(!['submitted','preparing','ready','completed','cancelled'].includes(status))fail(422,'Invalid arrival status.');if(status==='ready'&&items.some(i=>!['purchased','stocked'].includes(i.status)))fail(422,'Mark every selected item purchased before completing arrival preparation.');if(status==='ready'&&roomStatus.some(r=>!r.ready))fail(422,'Mark every residence room ready before completing arrival preparation.');if(status==='ready'&&!b.confirmNeeds)fail(422,'Confirm all additional preparation needs are complete.');run('UPDATE arrivals SET items=?,room_status=?,status=?,version=version+1 WHERE id=?',JSON.stringify(items),JSON.stringify(roomStatus),status,row.id);audit(user,'arrival.updated',row.id);result={ok:true};}
 else if(p==='/api/maintenance'){roles(user,'admin','employee');property(user,b.propertyId,'operate');if(!['Weekly','Monthly','Quarterly','Annual'].includes(b.frequency))fail(422,'Choose a frequency.');const key=id();run('INSERT INTO maintenance_plans VALUES(?,?,?,?,?,?,?)',key,b.propertyId,text(b.title,'Maintenance title',200),b.frequency,date(b.nextDue),1,now());audit(user,'maintenance.created',key);result={id:key};}
 else if(p==='/api/maintenance/generate'){roles(user,'admin','employee');const row=entity(user,'maintenance_plans',b.id,'operate');result=transaction(()=>{const existing=get('SELECT * FROM maintenance_occurrences WHERE plan_id=? AND due_date=?',row.id,row.next_due);if(existing)return {id:existing.work_order_id};const key=id();run('INSERT INTO work_orders(id,property_id,title,due_date,created_by,created_at) VALUES(?,?,?,?,?,?)',key,row.property_id,row.title,row.next_due,user.id,now());run('INSERT INTO maintenance_occurrences VALUES(?,?,?,?)',id(),row.id,row.next_due,key);audit(user,'maintenance.scheduled',key);return {id:key};});}
 else if(p==='/api/maintenance/run-due'){roles(user,'admin','employee');const until=date(b.until||new Date().toISOString().slice(0,10));const plans=all("SELECT * FROM maintenance_plans WHERE active=1 AND next_due<=?",until).filter(plan=>{try{property(user,plan.property_id,'operate');return true;}catch{return false;}});const generated=[];transaction(()=>{for(const plan of plans){const due=plan.next_due;const existing=get('SELECT * FROM maintenance_occurrences WHERE plan_id=? AND due_date=?',plan.id,due);let workId=existing?.work_order_id;if(!workId){workId=id();run('INSERT INTO work_orders(id,property_id,title,due_date,created_by,created_at) VALUES(?,?,?,?,?,?)',workId,plan.property_id,plan.title,due,user.id,now());run('INSERT INTO maintenance_occurrences VALUES(?,?,?,?)',id(),plan.id,due,workId);audit(user,'maintenance.scheduled',workId);generated.push(workId);}const following=nextDue(due,plan.frequency);run('UPDATE maintenance_plans SET next_due=? WHERE id=? AND next_due=?',following,plan.id,due);}});result={until,generatedCount:generated.length,workOrderIds:generated};}
 else if(p==='/api/invoices'){roles(user,'admin');if(!get('SELECT 1 FROM clients WHERE id=? AND organization_id=?',b.clientId,user.organization_id))fail(422,'Choose a family.');if(!Number.isSafeInteger(b.amountMinor)||b.amountMinor<=0)fail(422,'Amount must be greater than zero.');const key=id();run('INSERT INTO invoices VALUES(?,?,?,?,?,?,?,?,?)',key,user.organization_id,b.clientId,text(b.number,'Invoice number',80),text(b.description,'Description',1000),b.amountMinor,date(b.dueDate),'USD',now());audit(user,'invoice.created',key);result={id:key};}
 else if(p==='/api/payments'){roles(user,'admin');result=transaction(()=>{const invoice=get('SELECT * FROM invoices WHERE id=? AND organization_id=?',b.invoiceId,user.organization_id);if(!invoice)fail(404,'Invoice not found.');const paid=get('SELECT COALESCE(SUM(amount_minor),0) paid FROM payments WHERE invoice_id=?',invoice.id).paid;if(!Number.isSafeInteger(b.amountMinor)||b.amountMinor<=0||b.amountMinor>invoice.amount_minor-paid)fail(422,'Payment exceeds the outstanding balance or is invalid.');const key=id();run('INSERT INTO payments VALUES(?,?,?,?,?,?)',key,invoice.id,b.amountMinor,note(b.reference,200),user.id,now());audit(user,'payment.recorded',key);return {id:key};});}
 else if(p==='/api/notes'){roles(user,'admin','employee');property(user,b.propertyId,'operate');const key=id();run('INSERT INTO notes VALUES(?,?,?,?,?)',key,b.propertyId,text(b.body,'Note'),user.id,now());audit(user,'note.created',key);result={id:key};}
 else if(p==='/api/notifications/read'){run('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?',now(),b.id,user.id);result={ok:true};}
 else fail(404,'Endpoint not found.');
 return json(res,201,result);
}
function validateAnswers(answers){if(!Array.isArray(answers)||answers.length!==template.length)fail(422,'Checklist does not match the template.');return template.map(t=>{const a=answers.find(x=>x.key===t.key);if(!a||!['unchecked','pass','monitor','attention','na'].includes(a.status))fail(422,'Invalid inspection result.');return {...t,status:a.status,note:note(a.note)};});}

const server=http.createServer(async(req,res)=>{
 try{
  const host=req.headers.host||'';const url=new URL(req.url,'http://'+host);
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');
  const localHost=process.env.ESTATEOS_HOST||'127.0.0.1';
  if(localHost==='127.0.0.1'&&!/^(127\.0\.0\.1|localhost)(:\d+)?$/.test(host))fail(403,'Invalid host.');
  if(req.method!=='GET'&&req.method!=='HEAD'){const origin=req.headers.origin;if(!origin||new URL(origin).host!==host)fail(403,'Same-origin request required.');if(!String(req.headers['content-type']||'').startsWith('application/json'))fail(415,'JSON content required.');}
  if(url.pathname.startsWith('/api/'))return await api(req,res,url,actor(req));
  const names={'/':'live.html','/live.js':'live.js','/live.css':'live.css'};const file=names[url.pathname];if(!file)fail(404,'Page not found.');
  res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob: data:; connect-src 'self' https://nominatim.openstreetmap.org; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");
  res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css':'text/javascript','Cache-Control':'no-store'});fs.createReadStream(path.join(root,'public',file)).pipe(res);
 }catch(error){if(res.headersSent){res.end();return;}const status=error.status||500;if(status===500)console.error('Request failed:',error.message);json(res,status,{error:status===500?'The action could not be saved. Check the server log.':error.message});}
});
const port=Number(process.env.PORT||4317),host=process.env.ESTATEOS_HOST||'127.0.0.1';
if(host!=='127.0.0.1'&&(!process.env.ESTATEOS_SETUP_KEY||process.env.ESTATEOS_SETUP_KEY.length<24||process.env.ESTATEOS_SECURE_COOKIES!=='1'))throw Error('Nonlocal hosting requires a strong setup key, HTTPS termination and secure cookies. Complete the production deployment review first.');
server.listen(port,host,()=>console.log(`EstateOS running at http://${host}:${server.address().port}`));
process.on('SIGTERM',()=>server.close(()=>{db.close();process.exit(0);}));


