ALTER TABLE properties ADD COLUMN street_address TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN address_line2 TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN state TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN postal_code TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN country TEXT NOT NULL DEFAULT 'United States';
